CREATE TABLE [dbo].[TBMATERIA] (
    [NUMERO]            INT         IDENTITY (1, 1) NOT NULL,
    [NOME]              NCHAR (100) NOT NULL,
    [SERIE]             INT         NOT NULL,
    [DISCIPLINA_NUMERO] INT         NOT NULL,
    PRIMARY KEY CLUSTERED ([NUMERO] ASC),
    CONSTRAINT [FK_TBMATERIA] FOREIGN KEY ([DISCIPLINA_NUMERO]) REFERENCES [dbo].[TBDISCIPLINA] ([NUMERO])
);

